name: Docker Image CI

on:
  push:
    tags:
      - '*'
 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       # Get the repository's code
      - name: Checkout
        uses: actions/checkout@v3
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker meta
        id: ezkonnect-ui # you'll use this in the next step
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            resdenia/ezkonnect
          flavor: |
            latest=false
          # Docker tags based on the following events/attributes
          
      - name: Build and push amd64 with tag of version
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.ezkonnect-ui.outputs.tags }}
          labels: ${{ steps.ezkonnect-ui.outputs.labels }}

      - name: Build and push amd64 latest
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: resdenia/ezkonnect-ui:latest
          labels: ${{ steps.ezkonnect-ui.outputs.labels }}